[project]
name = "c4ffein-python-snippets"
version = "0.0.1"
authors = [
  { name="c4ffein", email="c4ffein@gmail.com" },
]
description = "Python snippets that don't deserve to get released on PyPI"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/c4ffein/python-snippets"
Issues = "https://github.com/c4ffein/python-snippets"

[project.optional-dependencies]
dev = [
    "ruff==0.5.1",
]

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
lint.select = [
    "B",    # flake8-bugbear
    "C",    # flake8-comprehensions
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "FURB", # refurb
    "I",    # isort
    "PTH",  # flake8-use-pathlib
    "UP",   # pyupgrade
    "W",    # pycodestyle warnings
]
line-length = 120

[tool.ruff.lint.per-file-ignores]
"src/pinned_ssl_context.py" = ["C901", "E731"]  # No complexity check, allow lambda definition
